version: 0.8.{build}

branches:
  only:
  - develop
  
image: Visual Studio 2017

configuration: 
  - Release

platform: x86

install:
  - git submodule update --init --recursive

before_build:
- sh: >-
    cd BWAPI4JBridge/ && \
    msbuild BWAPI4JBridge/externals/bwapi/bwapi/bwapi.sln /t:BWAPI;BWAPIClient /p:Configuration=Release_Pipeline && \
    
    cd externals/bwem/ && \
    mkdir build/ && cd build/ & \
    cmake .. && \
    msbuild build/BWEM.sln /p:Configuration=Release && \
    cd ../../../ && \

    mkdir build/ && cd build/ && \
    cmake .. -DBWAPI4JBRIDGE_ENABLE_LOGGER=1
    
build:
  project: BWAPI4JBridge/build/BWAPI4JBridge.sln
  parallel: true
  verbosity: minimal
