version: 0.8.{build}

branches:
  only:
  - develop
  
image: 
  - Visual Studio 2017

install:
  - git submodule update --init --recursive
 
build_script:
- cmd: >-
    cd BWAPI4J
    
    ./gradlew clean buildVanillaBridgeForWindows
