version: 0.8.{build}

branches:
  only:
  - develop
  
image: 
  - Visual Studio 2017

install:
  - git submodule update --init --recursive
 
build_script:
- cmd: >-
    msbuild /m "/t:BWAPI,BWAPIClient" /p:Configuration=Release_Pipeline BWAPI4JBridge/externals/bwapi/bwapi/bwapi.sln

    mkdir "BWAPI4JBridge\externals\bwem\build"
    
    cd "BWAPI4JBridge\externals\bwem\build"
    
    cmake -G "Visual Studio 15 2017" ..
    
    cmake --build . --config "Release"
    
    cd ..\..\..

    mkdir build
    
    cd build
    
    cmake -G "Visual Studio 15 2017" -DBWAPI4JBRIDGE_ENABLE_LOGGER=1 ..
    
    cmake --build . --config "Release"
