version: 0.8.{build}

branches:
  only:
  - develop
  
image: Visual Studio 2017

install:
  - git submodule update --init --recursive
 
before_build:
- ps: >-
    msbuild /m /t:BWAPI;BWAPIClient /p:Configuration=Release_Pipeline BWAPI4JBridge/externals/bwapi/bwapi/bwapi.sln

    mkdir BWAPI4JBridge/externals/bwem/build
    cd BWAPI4JBridge/externals/bwem/build
    cmake -G "Visual Studio 15 2017" ..
    msbuild /m /p:Configuration=Release BWEM.sln
    cd ../../../
    
    mkdir build
    cd build
    cmake -G "Visual Studio 15 2017" -DBWAPI4JBRIDGE_ENABLE_LOGGER=1 ..

configuration: 
  - Release

platform: x86
    
build:
  project: BWAPI4JBridge/build/BWAPI4JBridge.sln
  parallel: true
  verbosity: minimal
