version: 0.8.{build}

branches:
  only:
  - develop
  
image: Visual Studio 2017

configuration: 
  - Release

platform: x86

install:
  - git submodule update --init --recursive

before_build:
- git submodule update --init --recursive
- ps: >-
    msbuild BWAPI4JBridge/externals/bwapi/bwapi/bwapi.sln /t:BWAPI;BWAPIClient /p:Configuration=Release_Pipeline
- sh: >-
    mkdir BWAPI4JBridge/externals/bwem/build
    cd BWAPI4JBridge/externals/bwem/build
    cmake -G "Visual Studio 15 2017" ..
- ps: >-  
    msbuild BWAPI4JBridge/externals/bwem/build/BWEM.sln /p:Configuration=Release
- sh: >-
    mkdir BWAPI4JBridge/build
    cd BWAPI4JBridge/build
    cmake -G "Visual Studio 15 2017" -DBWAPI4JBRIDGE_ENABLE_LOGGER=1 ..
    
build:
  project: BWAPI4JBridge/build/BWAPI4JBridge.sln
  parallel: true
  verbosity: minimal
