version: 0.8.{build}

branches:
  only:
  - develop
  
image: Visual Studio 2017

install:
  - git submodule update --init --recursive
 
before_build:
- ps: >-
    .\appveyor_prebuild.ps

configuration: 
  - Release

platform: x86
    
build:
  project: BWAPI4JBridge/build/BWAPI4JBridge.sln
  parallel: true
  verbosity: minimal
