/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwem_map_MapInitializerImpl */

#ifndef _Included_bwem_map_MapInitializerImpl
#define _Included_bwem_map_MapInitializerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwem_map_MapInitializerImpl
 * Method:    initialize_native
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bwem_map_MapInitializerImpl_initialize_1native
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
