/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwta_BaseLocation */

#ifndef _Included_bwta_BaseLocation
#define _Included_bwta_BaseLocation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwta_BaseLocation
 * Method:    getGroundDistance
 * Signature: (Lbwta/BaseLocation;)D
 */
JNIEXPORT jdouble JNICALL Java_bwta_BaseLocation_getGroundDistance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bwta_BaseLocation
 * Method:    getAirDistance
 * Signature: (Lbwta/BaseLocation;)D
 */
JNIEXPORT jdouble JNICALL Java_bwta_BaseLocation_getAirDistance
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
