/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwta_Polygon */

#ifndef _Included_bwta_Polygon
#define _Included_bwta_Polygon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwta_Polygon
 * Method:    getNearestPoint
 * Signature: (JII)[I
 */
JNIEXPORT jintArray JNICALL Java_bwta_Polygon_getNearestPoint
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
