/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_lingala_zip4j_core_ZipFile */

#ifndef _Included_net_lingala_zip4j_core_ZipFile
#define _Included_net_lingala_zip4j_core_ZipFile
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
