/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_DamageEvaluator */

#ifndef _Included_org_openbw_bwapi4j_DamageEvaluator
#define _Included_org_openbw_bwapi4j_DamageEvaluator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openbw_bwapi4j_DamageEvaluator
 * Method:    getDamageFrom_native
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_DamageEvaluator_getDamageFrom_1native__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_DamageEvaluator
 * Method:    getDamageFrom_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_DamageEvaluator_getDamageFrom_1native__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_DamageEvaluator
 * Method:    getDamageFrom_native
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_DamageEvaluator_getDamageFrom_1native__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_DamageEvaluator
 * Method:    getDamageTo_native
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_DamageEvaluator_getDamageTo_1native__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_DamageEvaluator
 * Method:    getDamageTo_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_DamageEvaluator_getDamageTo_1native__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_DamageEvaluator
 * Method:    getDamageTo_native
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_DamageEvaluator_getDamageTo_1native__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
