/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_BWMap */

#ifndef _Included_org_openbw_bwapi4j_BWMap
#define _Included_org_openbw_bwapi4j_BWMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openbw_bwapi4j_BWMap
 * Method:    isVisible
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openbw_bwapi4j_BWMap_isVisible
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_BWMap
 * Method:    hasPath
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openbw_bwapi4j_BWMap_hasPath
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_BWMap
 * Method:    canBuildHere
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openbw_bwapi4j_BWMap_canBuildHere
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
