/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_BW */

#ifndef _Included_org_openbw_bwapi4j_BW
#define _Included_org_openbw_bwapi4j_BW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openbw_bwapi4j_BW
 * Method:    startGame
 * Signature: (Lorg/openbw/bwapi4j/BW;)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_BW_startGame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_openbw_bwapi4j_BW
 * Method:    getUnitTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_openbw_bwapi4j_BW_getUnitTypes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
