/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_BW_Property */

#ifndef _Included_org_openbw_bwapi4j_BW_Property
#define _Included_org_openbw_bwapi4j_BW_Property
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
