/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_unit_Unit */

#ifndef _Included_org_openbw_bwapi4j_unit_Unit
#define _Included_org_openbw_bwapi4j_unit_Unit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openbw_bwapi4j_unit_Unit
 * Method:    issueCommand
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openbw_bwapi4j_unit_Unit_issueCommand
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
