/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_BWMapImpl */

#ifndef _Included_org_openbw_bwapi4j_BWMapImpl
#define _Included_org_openbw_bwapi4j_BWMapImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    isBuildable
 * Signature: (IIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openbw_bwapi4j_BWMapImpl_isBuildable
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    isVisible
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openbw_bwapi4j_BWMapImpl_isVisible
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    hasPath
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openbw_bwapi4j_BWMapImpl_hasPath
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    canBuildHere
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openbw_bwapi4j_BWMapImpl_canBuildHere
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
