/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_MapDrawer */

#ifndef _Included_org_openbw_bwapi4j_MapDrawer
#define _Included_org_openbw_bwapi4j_MapDrawer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openbw_bwapi4j_MapDrawer
 * Method:    drawCircleMap_native
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_MapDrawer_drawCircleMap_1native__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_MapDrawer
 * Method:    drawCircleMap_native
 * Signature: (IIIIZ)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_MapDrawer_drawCircleMap_1native__IIIIZ
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_openbw_bwapi4j_MapDrawer
 * Method:    drawBoxMap_native
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_MapDrawer_drawBoxMap_1native__IIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_MapDrawer
 * Method:    drawBoxMap_native
 * Signature: (IIIIIZ)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_MapDrawer_drawBoxMap_1native__IIIIIZ
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_openbw_bwapi4j_MapDrawer
 * Method:    drawBoxScreen_native
 * Signature: (IIIIIZ)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_MapDrawer_drawBoxScreen_1native
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_openbw_bwapi4j_MapDrawer
 * Method:    drawLineMap_native
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_MapDrawer_drawLineMap_1native
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_MapDrawer
 * Method:    drawTextMap_native
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_MapDrawer_drawTextMap_1native
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     org_openbw_bwapi4j_MapDrawer
 * Method:    drawTextScreen_native
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_MapDrawer_drawTextScreen_1native
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     org_openbw_bwapi4j_MapDrawer
 * Method:    setTextSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_MapDrawer_setTextSize
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
