/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_unit_Unit_TrainingSlot */

#ifndef _Included_org_openbw_bwapi4j_unit_Unit_TrainingSlot
#define _Included_org_openbw_bwapi4j_unit_Unit_TrainingSlot
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
