/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_BW */

#ifndef _Included_org_openbw_bwapi4j_BW
#define _Included_org_openbw_bwapi4j_BW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openbw_bwapi4j_BW
 * Method:    startGame
 * Signature: (Lorg/openbw/bwapi4j/BW;)V
 */
JNIEXPORT void JNICALL Java_org_openbw_bwapi4j_BW_startGame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_openbw_bwapi4j_BW
 * Method:    getAllUnitsData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_openbw_bwapi4j_BW_getAllUnitsData
  (JNIEnv *, jobject);

/*
 * Class:     org_openbw_bwapi4j_BW
 * Method:    getAllPlayersData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_openbw_bwapi4j_BW_getAllPlayersData
  (JNIEnv *, jobject);

/*
 * Class:     org_openbw_bwapi4j_BW
 * Method:    getGameData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_openbw_bwapi4j_BW_getGameData
  (JNIEnv *, jobject);

/*
 * Class:     org_openbw_bwapi4j_BW
 * Method:    getPlayerName
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openbw_bwapi4j_BW_getPlayerName
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openbw_bwapi4j_BW
 * Method:    getResearchStatus
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_openbw_bwapi4j_BW_getResearchStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openbw_bwapi4j_BW
 * Method:    getUpgradeStatus
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_openbw_bwapi4j_BW_getUpgradeStatus
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
