/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_MapDrawer_TextSize */

#ifndef _Included_org_openbw_bwapi4j_MapDrawer_TextSize
#define _Included_org_openbw_bwapi4j_MapDrawer_TextSize
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
