/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openbw_bwapi4j_BWMapImpl */

#ifndef _Included_org_openbw_bwapi4j_BWMapImpl
#define _Included_org_openbw_bwapi4j_BWMapImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    _isBuildable
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_BWMapImpl__1isBuildable
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    _isExplored
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_BWMapImpl__1isExplored
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    _isVisible
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_BWMapImpl__1isVisible
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    _hasPath
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_BWMapImpl__1hasPath
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    _canBuildHere
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_BWMapImpl__1canBuildHere__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openbw_bwapi4j_BWMapImpl
 * Method:    _canBuildHere
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_openbw_bwapi4j_BWMapImpl__1canBuildHere__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
