set DEV_CMD_BAT="..\\..\\..\\..\\VsDevCmd.bat"
set TARGET_BUILD_DIRECTORY="externals\\openbw\\bwapi\\build"
set TARGET_SOLUTION="BWAPI.sln"

IF NOT EXIST %TARGET_BUILD_DIRECTORY% (
mkdir %TARGET_BUILD_DIRECTORY%
)

cd %TARGET_BUILD_DIRECTORY%
cmake .. -DCMAKE_BUILD_TYPE=Release -DOPENBW_DIR=../../openbw -DOPENBW_ENABLE_UI=1 -DSDL2_INCLUDE_DIR=%SDL2_INCLUDE_DIR% -DSDL2_LIBRARY=%SDL2_LIBRARY%

IF EXIST %TARGET_SOLUTION% (
%DEV_CMD_BAT%
msbuild %TARGET_SOLUTION% /p:Configuration=Release
)
