if (NOT BWAPI4JBRIDGE_CMAKE_INCLUDE)
set(BWAPI4JBRIDGE_CMAKE_INCLUDE 1)

if_unset_then_set(BWAPI4JBRIDGE_SRC_DIR ${CMAKE_CURRENT_LIST_DIR}/src)

file(GLOB_RECURSE BWAPI4JBRIDGE_SRCS
    ${BWAPI4JBRIDGE_SRC_DIR}/*.h
    ${BWAPI4JBRIDGE_SRC_DIR}/*.cpp
)

add_library(${PROJECT_NAME} SHARED ${BWAPI4JBRIDGE_SRCS})

endif()
